name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        qt-binding: ['pyside2', 'pyside6']
      fail-fast: false  # 允许其他版本继续测试，即使某个版本失败
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
    
    - name: Run tests
      run: |
        nox -s test -- --qt_binding=${{ matrix.qt-binding }}
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella-py${{ matrix.python-version }}-${{ matrix.qt-binding }}
        fail_ci_if_error: true
